### ISSUE TITLE
bravo!

### ISSUE THREAD

**Issue by helgasoft** [Rafael-Ayala/asteRisk#2]
Hello team, you are GIANTS!  🚀🚀
Astrodynamics is not for everyone, thank you for opening the heavens for us.
Just finished a [**3D demo**](https://rpubs.com/echarty/satellites) using **asteRisk**.

![sat3D](https://user-images.githubusercontent.com/13038071/146492052-1df01ad8-91a3-4f82-bfbb-182aafa857d6.jpg)

Some questions/observations along the way. We are using Windows 10 with RStudio for development.

1. asteRiskData::getLatestSpaceData
  > _utils::nsl  This function is not available on Windows._
2. Commented out **nsl** in (1) and went on, but got another error
  > _Updating Earth positions ..._
   > _Error in bindingIsLocked(x, ns) : no binding for "earthPositions"_
3. **sgdp4** keplerAccuracy & maxKeplerIterations do not seem to have noticeable impact on calculation speed?  Kind of strange...
4. TEMEtoLATLON - why is the _dateTime_ parameter necessary? 
   We had it set to "2006-06-27 00:58:29.34", (a value from your demos) because we did not know what to use there. Then it looked silly, so we replaced it with _epochDateTime_ and... ran in all sorts of trouble and mysterious errors. Now we are back to silly-but-stable June 27, 2006. Magic in the air...
   
👍👍👍

**Comment by Rafael-Ayala** [comment]
@helgasoft 

Hello, thanks a lot for your very positive comments and interest in our software! 

The 3D demo looks _**amazing**_ ! I built some interactive trajectory plots with plotly recently, but this looks impressive

I will be happy to answer your questions/fix the problems you found:

> 1. asteRiskData::getLatestSpaceData
> utils::nsl This function is not available on Windows.

Thanks for pointing this out. I have now updated asteRiskData with the portable option **nslookup**, from the **curl** package, which should work on all platforms

> 2. Commented out nsl in (1) and went on, but got another error
> Updating Earth positions ...
> Error in bindingIsLocked(x, ns) : no binding for "earthPositions"

Do you have the latest version of the complementary data package, asteRiskData, installed? Could you please try to remove it if you have it, and reinstall by running the following?

`install.packages("asteRiskData", repos="https://rafael-ayala.github.io/drat/")`

Let me know if that fixes the issue! If not, we will investigate further

> 3. sgdp4 keplerAccuracy & maxKeplerIterations do not seem to have noticeable impact on calculation speed? Kind of strange...

Interesting observation! However, solving Kepler's equation (by Newton's method) is just a minor part of the SGP4 and SDP4 propagators. Additionally, I think usually convergence is reached in just a few iterations, less than 5. I left the option to change these arguments for potential rare, edge cases where more iterations would be required, but this is probably not required for a majority of situations.

> 4. TEMEtoLATLON - why is the dateTime parameter necessary?
We had it set to "2006-06-27 00:58:29.34", (a value from your demos) because we did not know what to use there. Then it looked silly, so we replaced it with epochDateTime and... ran in all sorts of trouble and mysterious errors. Now we are back to silly-but-stable June 27, 2006. Magic in the air...

Good question! In summary, the main reason is that the TEME frame is an inertial frame of reference, i.e., it does not rotate with Earth, while geodetic latitude and longitude are a non-inertial frame of reference that rotates with Earth (i.e., a pair of latitude and longitude always represents the same position on the surface of Earth). In order to convert from an inertial frame to a non-inertial one, we need to now the position of the Earth at that instant. It gets even more complex when we consider not only Earth rotation, but also precession, nutation and polar motion. So in order to perform the conversion correctly, we need to provide the date and time for which the position in TEME corresponds. You can test this for example by adding 12 hours to the example epochDateTime. You will notice that the longitude value is completely different. asteRisk handles all of this internally, but it requires Earth orientation parameters. 

When you say you replaced the original value with _epochDateTime_, do you mean with the epoch specified in a TLE file? If so, if it was a recent TLE file, it probably has an epoch in this year (2021). The values of Earth orientation parameters bundled with asteRiskData include data up to at some point in 2018 I believe. The internal data tables are updated by running getLatestSpaceData. The errors you are getting are probably due to the fact that the conversion function tried to look for Earth orientation parameters for dates that did not exist at that point in the table of Earth orientation parameters. These problems will very likely go away after being able to successfully run getLatestSpaceData. 

Let me know if the above suggestions and updated version of asteRiskData fix your problem! Otherwise, we will look for a solution :)

**Comment by helgasoft** [comment]
Thank you for the kind words about our demo.

I did follow your instructions for (1) and (2).  Now flawless with latest asteRiskData v.0.1.1 
```r
> asteRiskData::getLatestSpaceData()
Updating Earth positions ...
Updating space weather data ...
Updating solar storms data ...
Updating geomagnetic storms data ...
All data successfully updated
```
Regarding (4) - yes, the TEMEtoLATLON parameter **dateTime** is very important indeed. I'm using now ```dateTime <- as.character(as.POSIXlt(Sys.time(), tz='UTC'))``` and results are accurate. I would suggest however a different explanation for _dateTime_ in the docs. Currently it says
_"Date-time string with the date and time in UTC corresponding to the provided position vector. "_
which was confusing for an amateur like me.

And another gentle suggestion for **readTLE**. I had to extend it with an additional parameter **n3** like so:
```r
readTLE2 <- function (filename, n3) {
  lines <- readLines(filename, n3) ....
```
This was done to speed up reading file _https://www.celestrak.com/NORAD/elements/active.txt_ which is 17MB.  From those 4900+ entries I needed just the first 450. So maybe adding such parameter is worth considering.

**Comment by Rafael-Ayala** [comment]
@helgasoft 

Thanks a lot for your comments and suggestions. Great to hear that the issues when updating Earth orientation parameters are fixed!

I have now added additional explanations to what the date-time required by some functions for conversion between reference frames is, as well as why this is required. Hopefully it's clearer now!

I have also pushed a new version with a new argument for **readTLE**, named _maxTLEs_, which allows to specify a maximum number of TLEs to read from the file. Let me know if there is any issues with it!

Regarding the definition for **dateTime** that you mentioned, from it I assume you are aiming to display the position of satellites in real time as calculated with SGP4/SDP4, right? If so, it makes sense to use indeed such value for **dateTime**. If not, however, the most accurate would be to use the time that corresponds to the propagated position. This can be calculated by adding (or subtracting, for propagation into the past) the number of seconds of propagation time to the epoch dateTime string obtained from each TLE. Something like this:

```r
## For example, for a propagation time of 10 minutes into the future:
targetTime <- 10
## The dateTime value for conversion between TEME and geodetic coordinates would be:
dateTime <- as.character(as.POSIXct(molniya$dateTime, tz="UTC") + 60*targetTime)
```

Hopefully it makes sense!

I was also wondering if you would be interested in speed-up performances for the SGP4/SDP4 calculations, since you might be aiming to calculate the orbit of many satellites in real time. Let me know if this is the case, and I think it might be possible to obtain some significant speed-ups!

**Comment by helgasoft** [comment]
1) ok, readTLE, with _maxTLEs_ works.

2) question: how often **getLatestSpaceData** has to be run ? Seems like every hour I get this error
```Error in if (abs(lon) >= pi) { : missing value where TRUE/FALSE needed```
when executing sgdp4 + TEMEtoLATLON.  Then I re-run getLatestSpaceData and everything is back to normal (?!)

3) my observations about parameter **dateTime** of TEMEtoLATLON:
First, adding minutes to the time character string works (wow! didn't know), so no need for library _lubridate_.
Using directly your two-line code above however gave me the following twisted magenta orbit at start/end location:

![image](https://user-images.githubusercontent.com/13038071/147008128-4b1a9c5b-e00c-4329-8a9d-b0f26687440c.png)

After some more tweaking I realized the reason why.  Functions **sgdp4** and **TEMEtoLATLON** are used, at least by me, in tandem.
```r
  # epochDateTime comes from the TLE file, could be hours ago. Same with n0,M0,omega,etc.
  initial <- as.character(as.POSIXlt(epochDateTime))
  # target is the future time when we want the satellite position calculated
  target <- as.character(as.POSIXlt(Sys.time(), tz='UTC') + 60*minutes) 

  # calculate the position and velocity of the satellite <'target' minutes> later
  state_1day_TEME <- sgdp4(n0=n0, e0=e0, i0=i0, M0=M0, omega0=omega0, OMEGA0=OMEGA0,
                           Bstar=Bstar, initialDateTime=initial, targetTime=target)
  # now convert the results in TEME frame to geodetic latitude, longitude and altitude, 
  #  multiplying by 1000 to convert the km output of sgdp4 to meters
  
  #dateTime <- as.character(as.POSIXlt(Sys.time(), tz='UTC') + 60*minutes)   # incorrect
   dateTime <- as.character(as.POSIXlt(Sys.time(), tz='UTC'))   # correct
  coord <- TEMEtoLATLON(state_1day_TEME$position*1000, dateTime) 
```
The **targetTime** parameter of sgdp4 already requires a future time to calculate correct position and velocity. And that's when the minutes should be added.
If I add minutes again in **dateTime** for TEMEtoLATLON, then I end up with a twisted orbit because  the minutes have been added **twice**.

4) "speed-up performances for the SGP4/SDP4" - sure interested!  On an i5 Intel CPU it takes over 25 seconds now to calculate 60 minutes (incomplete orbits) for 68 satellites.

**Comment by Rafael-Ayala** [comment]
@helgasoft 

Thanks a lot for the new insights!

Regarding 2), in principle running getLatestSpaceData once at the beginning of a session will update the data to the latest available on CelesTrak, which are updated daily. But that also includes predicted values for every day up to 6 months into the future, so once should be fine. This is indeed rather strange. When you say you get the error every hour, do you mean for every block of 60 minutes of propagation you need to re-run getLatestSpaceData() before being able to propagate it correctly? If so, is each propagation block by any chance starting a new R-session? If this is the case, do you think it might be possible to make it so that all propagations are run in the same R-session? If not, I can try to look for a way to cache the updated data locally, so that we do not get back to the original bundled version, which does not contain current data.

Regarding 3), I see, you are providing directly a date-time string to **targetTime**. In this case, your way is indeed correct, since adding minutes again to this would indeed be a duplication. 

I will get started with optimizing the SGP4/SDP4 calculations! I believe your use case is very interesting, since it is aiming for a real-time application, and therefore allows us to identify potential improvements that were not evident without the need to get results in real-time

**Comment by helgasoft** [comment]
1) Regarding the error in (2) - identified the problem. Here is how to replicate: 

- open new session in RStudio
- run code from the TEMEtoLATLON documentation example. The last date **year** has been changed from 2006 to 2021:
```r
library(asteRisk)
if(requireNamespace("asteRiskData", quietly = TRUE)) {
# The following orbital parameters correspond to an object with NORAD catalogue
# number 24208 (Italsat 2) the 26th of June, 2006 at 00:58:29.34 UTC.

n0 <- 1.007781*((2*pi)/(1440))  # Multiplication by 2pi/1440 to convert to radians/min
e0 <- 0.002664 # mean eccentricity at epoch
i0 <- 3.8536*pi/180 # mean inclination at epoch in radians
M0 <- 48.3*pi/180 # mean anomaly at epoch in radians
omega0 <- 311.0977*pi/180 # mean argument of perigee at epoch in radians
OMEGA0 <- 80.0121*pi/180 # mean longitude of ascending node at epoch in radians
Bstar <- 1e-04 # drag coefficient
epochDateTime <- "2006-06-26 00:58:29.34"

# Let´s calculate the position and velocity of the satellite 1 day later

state_1day_TEME <- sgdp4(n0=n0, e0=e0, i0=i0, M0=M0, omega0=omega0, OMEGA0=OMEGA0,
                         Bstar=Bstar, initialDateTime=epochDateTime, targetTime=1440)

# We can now convert the results in TEME frame to geodetic latitude, longitude
# and altitude, previously multiplying by 1000 to convert the km output of 
# sgdp4 to m

state_1day_geodetic <- TEMEtoLATLON(state_1day_TEME$position*1000, 
                                    "2021-06-27 00:58:29.34")
}

Error in if (abs(lon) >= pi) { : missing value where TRUE/FALSE needed
```
- run _getLatestSpaceData()_
- repeat the last line of code ```state_1day_geodetic <- TEMEtoLATLON(state_1day_TEME$position*1000, "2021-06-27 00:58:29.34")``` - it does not raise an error anymore.

2) suggestion for **TEMEtoLATLON**:  
change the above error message to something more precise, like "please run getLatestSpaceData() first"
 
3) suggestion for **getLatestSpaceData**: 
add a boolean flag (default=FALSE) to do only first section "Updating Earth positions".
Of course this comes from my (narrow) specific use case in attempt to accelerate speed, since I'm not interested in the others (weather,solar,geomagnetic).

**Comment by Rafael-Ayala** [comment]
@helgasoft 

Indeed, the problem with running the example by changing the year to 2021 is due to not having run getLatestSpaceData() first. I have now updated this so that an informative error message will be given when attempting to perform a conversion for a date for which Earth orientation parameters are not available.

I have also updated getLatestSpaceData. It now accepts an argument **targets**, which should be a character vector containing one or more of the following elements: all" (to update all data), "EOP" (Earth orientation parameters), "SW" (space weather), "SS" (solar storms) or "GS" (geomagnetic storms). By default, all data are updated. So you can now provide `targets="EOP"` to speed things up :)

Are you now able to run things smoothly by simply running getLatestSpaceData() once at the beginning of the session? Or are you still seeing an error every hour?

**Comment by helgasoft** [comment]
Thank you for fulfilling my Santa wishes list so quickly 🎅  
Looks like the new code is not published yet, will take a look when available.

About _"error every hour"_ probably it was me - a habit to clean the environment from time to time and start fresh with a new R session.  No worries, things run smoothly now.

**Comment by Rafael-Ayala** [comment]
@helgasoft 

Sorry, I finished the changes but forgot to push them! They are all published now. You will also need to install the latest version of asteRiskData, for which I recommend deleting the currently installation and re-installing as before (it should then install version 0.1.3).

No problem! I really like the improvements that have resulted from your suggestions. I am currently looking into the best ways to obtain speed-ups for the SGP4/SDP4 propagators. There is certainly room for large improvements, but I need to look into the best way to do it keeping in mind that for your use case you are likely interested in obtaining results in as close as possible to in real-time, for an extended period, and for multiple satellites simultaneously.
