### ISSUE TITLE
getLatestSpaceData

### ISSUE THREAD

**Issue by helgasoft** [Rafael-Ayala/asteRisk#4]
Looks like _getLatestSpaceData_ in **asteRiskData** still does not have the **targets** parameter.
```r
> library(asteRisk)
> library(asteRiskData)
Run getLatestSpaceData() to obtain the latest Earth orientation, space weather and solarstorms data

Attaching package: ‘asteRiskData’

The following object is masked from ‘package:asteRisk’:

    getLatestSpaceData

> 
> getLatestSpaceData('EOP')
Error in getLatestSpaceData("EOP") : unused argument ("EOP")
> asteRisk::getLatestSpaceData(targets='EOP')
Error in asteRiskData::getLatestSpaceData(targets = targets) : 
  unused argument (targets = targets)

```

**Comment by helgasoft** [comment]
### SOLVED
oops, my mistake, did not pay attention to your note to delete/reinstall the package.
The command is ```install.packages("asteRiskData", repos="https://rafael-ayala.github.io/drat/")```.
The latest version shows as "0.4" and now _getLatestSpaceData("EOP")_ works!

Keep thinking about the two packages...  
**asteRiskData** is pretty big at 89.5 MB compressed. Have you thought of loading conditionally chunks of data/code, only on demand (like with _readRDS_) ?

**Comment by Rafael-Ayala** [comment]
Indeed, asteRiskData is growing to worryingly large sizes. Unluckily, I expect it to grow even more as I add more functionalities. A large part of it comes from the very high precision gravity model for Earth, and upcoming high precision gravity model for the Moon (and possibly other celestial bodies).

Another possibility might be to split the data package into other smaller packages. This might even be my preferred option, since files over 100 MB will cause great issues since they cannot be uploaded to GitHub. 

I will look into this!

**Comment by Rafael-Ayala** [comment]
In fact I just checked and 85 out of the 89.5 MB are due to the JPL DE441 coefficients... It might all be solved to a reasonable situation by just placing the JPL development ephemerides into a third separate package

**Comment by helgasoft** [comment]
Our library _echarty_ loads Javascript extensions on demand through function _ec.init()_. When one needs the "3D" extension, the command is _ec.init(load='3D',...)_. The "3D" extension resides on the Internet and is not even part of our package. 

A similar scenario is possible for _asteRisk_, additional libraries like _asteRiskData_ **may** not be needed at all. Here is a proof-of-concept(POC) code:
```r
# loading data locally
load('C:\\Users\\user1\\Documents\\R\\win-library\\4.1\\asteRiskData\\data\\DE440coeffs.rda')
str(DE440coeffs)
	# num [1:12556, 1:1018] 2287185 2287217 2287249 2287281 2287313 ...
	# - attr(*, "dimnames")=List of 2
	# ..$ : NULL
	# ..$ : chr [1:1018] "startJD" "endJD" "MercuryS1XC1" "MercuryS1XC2" ...

# loading data remotely  (.RData is more recent version of .rda)
load(url('https://cdn.jsdelivr.net/gh/csgillespie/efficientR@master/extdata/07-rcpp_comparison.RData', 'rb'))
str(z)
	# Classes ‘microbenchmark’ and 'data.frame':	4000 obs. of  2 variables:
	# $ expr: Factor w/ 4 levels "mean(x)","mean_r(x)",..: 1 2 1 1 1 2 2 3 2 4 ...
	# $ time: num  25072 328763 7783 5468 4781 ..
```
Currently one has to run **getLatestSpaceData** for initialization anyway. This function could become the "data loader" controlled by the user thru parameters, for example like _getLatestSpaceData(target='DE440',...)_.
I think this solution will accommodate any future data additions, also making the project simpler with just **one package** _asteRisk_.

**Comment by Rafael-Ayala** [comment]
I see, this solution looks very interesting indeed! Most of the data would need to be somehow parsed, but I think it should be possible to somehow cache it locally, so that subsequent sessions could pick up from there (for data that is not periodically updated) without requiring again downloading and parsing. Will certainly look into this!

**Comment by helgasoft** [comment]
Yes, that's what we are doing with _ec.init_ - JS files are downloaded just once and all later sessions find and load them from disk.
